language: node_js
sudo: false
branches:
  only:
    - gh-pages # test gh-pages
    - /(.*)/   # test all branches
before_script:
  - npm install -g jsonlint
  - sudo apt-get update && sudo apt-get install azure-cli
script: jsonlint -q azuredeploy.json
        az login
