
language: node_js
sudo: false
branches:
  only:
    - gh-pages # test gh-pages
    - /(.*)/   # test all branches
before_script:
- sudo apt-get install apt-transport-https
- sudo apt-get update && sudo apt-get install azure-cli
script:az login 
