language: node_js
sudo: false
branches:
  only:
    - gh-pages # test gh-pages
    - /(.*)/   # test all branches
before_script:
  - npm install -g jsonlint
  template_link: 'https://raw.githubusercontent.com/azure/azure-quickstart-templates/master/201-web-app-github-deploy/azuredeploy.json'
