language: node_js
sudo: false
branches:
  only:
    - gh-pages # test gh-pages
    - /(.*)/   # test all branches
before_script:
  - npm install -g jsonlint
script: jsonlint -q https://github.com/MSidda/travis123/blob/master/azuredeploy.json
